import './js/films';
import './js/footer';
import './js/header';
import './js/modal-film';
import './js/modal-team';
import './js/spinner';
import './js/up-button';
import './js/pagination';
import './js/darkmode';
