import './js/films';
import './js/modal-film';
import './js/modal-team';
import './js/spinner';
import './js/up-button';
import './js/pagination';
import './js/refs';
import './js/darkmode';
import './js/save-buttons';
